personagem= [
        (0, 'elo', 0, 'semeador da peversao', 's', 9500, 'normal'),
        (1, 'satiro', 0, 'bardo', 'b', 150, 'normal'),
        (2, 'cyclops', 2, 'gigante desespero', 'b', 350, 'normal'),
        (3, 'vicio', 3, 'semeador do vicio', 'b', 3500, 'normal'),
        (4, 'freddy', 3, 'semeador do terror', 'b', 700, 'normal'),
        (5, 'ungoliant', 5, 'monarca da gula', 'a', 950, 'normal'),
        (6, 'naga', 5, 'semeador da distracao', 'b', 500, 'normal'),
        (7, 'evil santa', 7, 'guerreiro', 'b', 650, 'normal'),
        (8, 'recaida', 7, 'necromante', 'b', 400, 'normal'),
        (9, 'asagi', 9, 'semeador do odio', 's', 3000, 'normal'),
        (10, 'lavadeiromante', 9, 'necromante', 'c', 800, 'normal'),
        (11, 'serket', 11, 'monarca da inveja', 'a', 750, 'normal'),
        (12, 'estresse sombrio', 11, 'estresse sombrio', 'c', 0, 'normal'),
        (13, 'coelinho feral', 11, 'poeira', 'd', 0, 'normal'),
        (14, 'Hanzo sama', 14, 'monarca da ira', 'a', 350, 'normal'),
        (15, 'madame agonia', 15, 'semeador da agonia', 'a', 600, 'normal'),
        (16, 'goliath', 16, 'guerreiro', 'a', 800, 'normal'),
        (17, 'granit', 16, 'criatura da caverna', 'b', 150, 'normal'),
        (18, 'minotaur', 16, 'guerreiro', 'b', 50, 'normal'),
        (19, 'justia', 19, 'semeador da injustica', 'b', 200, 'normal'),
        (20, 'basilist', 19, 'lista basica', 'd', 0, 'normal'),
        (21, 'goblin', 19, 'ladrao de propositos', 'c', 750, 'normal'),
        (22, 'kitsune', 22, 'semeador de entorpecentes', 'b', 900, 'normal'),
        (23, 'clever', 22, 'semeador da distracao', 'b', 200, 'normal'),
        (24, 'defronowe', 24, 'succubus', 'a', 750, 'normal'),
        (25, 'heider', 25, 'monarca da avareza', 'a', 7500, 'normal'),
        (26, 'arryl', 25, 'guerreiro', 'a', 500, 'normal'),
        (27, 'vera', 25, 'guerreiro', 'b', 250, 'normal'),
        (28, 'tengu', 28, 'ladrao de conhecimento', 's', 550, 'normal'),
        (29, 'silene', 28, 'ladino', 'b', 950, 'normal'),
        (30, 'exaustao', 28, 'semeador do cansaco', 'b', 100, 'normal'),
        (31, 'Hipnos', 31, 'monarca da preguica', 'a', 750, 'normal'),
        (32, 'Hehta', 31, 'guerreiro', 'a', 450, 'normal'),
        (33, 'madame lotrix', 33, 'marionetista', 's', 3500, 'normal'),
        (34, 'zalidus', 33, 'guerreiro', 'a', 450, 'normal'),
        (35, 'strik', 33, 'semeador da agonia', 'b', 300, 'normal'),
        (36, 'ironknight', 36, 'devorador de orgulho', 'b', 150, 'normal'),
        (37, 'enlil', 37, 'manipuladora dos ventos', 'b', 300, 'normal'),
        (38, 'lilium', '38', 'monarca da luxuria', 'a', 750, 'morto'),
        (39, 'ismat', 39, 'monarca da soberba', 'a', 950, 'normal'),
        (40, 'Stheno', 40, 'semeador da distracao', 'a', 400, 'normal'),
        (41, 'lashna', 40, 'kraken do incompleto', 'a', 250, 'normal'),
        (42, 'djinn', 42, 'djinn', 'b', 300, 'normal'),
        (43, 'ainz ooal gown', 0, 'overlord', 's', 5000, 'morto'),
        (44, 'kronos', 9, 'overlord', 's', 3000, 'morto'),
        (45, 'slan', 24, 'overlord', 's', 900, 'morto'),
        (46, 'buddha', 28, 'overlord', 's', 0, 'morto'),
        (47, 'mukuro', 33, 'overlord', 's', 2000, 'controlado'),
        (48, 'hades', 5, 'estrategista', 'a', 700, 'controlado'),
        (49, 'espectro', 7, 'lord', 'b', 250, 'controlado'),
        (50, 'thanatus', 22, 'lord', 'b', 750, 'controlado'),
        (51, 'medico da peste', 0, 'medico', 'd', 950, 'controlado'),
        (52, 'hannibal lecter', 33, 'estrategista', 'c', 20, 'controlado'),
        (53, 'orlandeau', 5, 'guerreiro', 'b', 70, 'controlado'),
        (54, 'crocodile', 15, 'lord', 'b', 550, 'normal'),
        (55, 'davy jones', 16, 'lord', 'c', 400, 'controlado'),
        (56, 'kurama youko', 11, 'lord', 'a', 400, 'envenenado'),
        (57, 'malevola', 25, 'lord', 'c', 350, 'envenenado'),
        (58, 'rei da noite', 31, 'lord', 'a', 250, 'controlado'),
        (59, 'orochimaru', 37, 'lord', 'b', 550, 'controlado'),
        (60, 'dracula', 38, 'lord', 'a', 950, 'normal'),
        (61, 'morgana', 14, 'lord', 'c', 150, 'controlado'),
        (62, 'poseidon', 7, 'mago', 'a', 700, 'controlado'),
        (63, 'wonka', 3, 'lord', 'c', 900, 'controlado'),
        (64, 'zeus', 9, 'mago', 'a', 100, 'controlado'),
        (65, 'vecna', 5, 'lord', 'a', 950, 'petrificado'),
        (66, 'geralt de rivia', 11, 'guerreiro', 'c', 350, 'controlado'),
        (67, 'big boss', 14, 'ladino', 'c', 550, 'controlado'),
        (68, 'dante', 15, 'guerreiro', 'b', 50, 'controlado'),
        (69, 'harlequin', 16, 'guerreiro', 'd', 250, 'normal'),
        (70, 'orc', 2, 'guerreiro', 'c', 100, 'normal'),
        (71, 'misterio', 22, 'mago', 'c', 550, 'petrificado'),
        (72, 'jiraiya', 24, 'ladino', 'c', 300, 'controlado'),
        (73, 'baba yaga', 25, 'ladino', 'b', 750, 'controlado'),
        (74, 'felicia', 28, 'guerreiro', 'c', 350, 'controlado'),
        (75, 'zumbi', 19, None, 'e', 150, 'normal'),
        (76, 'lobo mal', 36, 'ladino', 'c', 50, 'normal'),
        (77, 'doppelganger', 39, 'mago', 'b', 450, 'normal'),
        (78, 'sub-zero', 40, 'guerreiro', 'c', 200, 'petrificado'),
        (79, 'carmilla', 37, 'guerreiro', 'b', 750, 'controlado'),
        (80, 'shinobi', 38, 'ladino', 'd', 350, 'normal'),
        (81, 'cyclops', 42, 'guerreiro', 'd', 50, 'controlado'),
        (82, 'alfred pennyworth', 33, 'mordomo', 'd', 150, 'controlado'),
        (83, 'cersei lannister', 0, 'estrategista', 'e', 1100, 'normal'),
        (84, 'ritsuko akagi', 33, 'cientista', 'e', 100, 'controlado'),
        (85, 'minoru kamiya', 33, 'medico', 'c', 150, 'normal'),
        (86, 'chrollo lucilfer', 0, 'mago', 'a', 350, 'controlado'),
        (87, 'tony stark', 38, 'ferreiro', 'd', 600, 'normal'),
        (88, 'bulma', 38, 'cientista', 'e', 950, 'normal'),
        (89, 'coracao gelado', 0, 'mago', 'b',450, 'normal'),
        (90, 'vito corleone', 9, 'estrategista', 'd', 800, 'controlado'),
        (91, 'mestre dos magos', 9, 'mago', 'a', 500, 'controlado'),
        (92, 'mercador do poder', 0, 'mercador', 'c', 900, 'controlado'),
        (93, 'cavaleiro sombrio', 0, 'guerreiro', 'a', 200, 'normal'),
        (94, 'andre de astora', 33, 'ferreiro', 'd', 150, 'controlado'),
        (95, 'sanji', 33, 'cozinheiro', 'b', 250, 'controlado'),
        (96, 'neferpitou', 0, 'medico', 'a', 300, 'controlado'),
        (97, 'david lindhagen', 9, 'mercador', 'e', 250, 'controlado'),
        (98, 'hamlet', 0, 'louco', 'e', 500, 'normal'),
        (99, 'thomas shelby', 33, 'mercador', 'd', 750, 'normal'),
        (100, 'amy farrah', 0, 'cientista', 'e', 200, 'controlado'),
        (101, 'light yagami', 24, 'estrategista', 'd', 100, 'controlado'),
        (102, 'shikamaru nara', 28, 'estrategista', 'c', 250, 'controlado'),
        (103, 'thrawn', 38, 'estrategista', 'd', 550, 'normal'),
        (104, 'angela ziegler', 9, 'medico', 'd', 700, 'controlado'),
        (105, 'beverly crusher', 38, 'medico', 'e', 600, 'normal'),
        (106, 'helen cho', 24, 'medico', 'e', 600, 'controlado'),
        (107, 'miia', 33, 'medico', 'd', 250, 'controlado'),
        (108, 'lobo da step', 0, 'guerreiro', 'a', 550, 'controlado')
]

